### ISSUE TITLE
速度にNaNが入ってしまう問題を修正

### ISSUE THREAD

**Issue by HansRobo** [ibis-ssl/crane#223]

**Comment by HansRobo** [comment]
どうやらゴールキーパーから出ているみたい。
target_xが-infになっている
```
- robot_id: 0
  local_goalie_enable: false
  enable_ball_centering_control: false
  local_planner_config:
    disable_collision_avoidance: false
    disable_goal_area_avoidance: true
    disable_placement_avoidance: false
    disable_ball_avoidance: true
    max_acceleration: 4.0
    max_velocity: 4.0
    max_omega: 1.0
    terminal_velocity: .nan
  chip_enable: true
  stop_flag: false
  lift_up_dribbler_flag: false
  kick_power: 0.4000000059604645
  dribble_power: 0.0
  target_velocity:
    x: .nan
    y: 9.105322051894404e-10
    theta: 0.0
  current_pose:
    x: -4.400000095367432
    y: -4.552661025947202e-10
    theta: 0.510811984539032
  enable_local_feedback: false
  target_x:
  - -.inf
  target_y:
  - 0.0
  target_theta:
  - 0.0
  latency_ms: 0.0
  current_ball_x: 12.077423095703125
  current_ball_y: 9.234363555908203
  motion_mode_enable: false
```
